#!/usr/bin/env python3
"""Generate the MDFourier profile (.mfn) for the PGM ICS2115 test signal.

The profile is derived entirely from util.mdfourier.signal so it always matches
the emitted signal.  Format follows MDFourierAudioBlockFile 2.3 (the same shape
as the stock console profiles such as mdfblocksGEN.mfn).

It can also emit a C header (the packed script + voice template + timer
constants) for the standalone testroms/pages/mdfourier.c demo page.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from util.mdfourier import mdf_signal as sig

DEFAULT_MFN = Path(__file__).resolve().parent / "pgm_mdfourier.mfn"
DEFAULT_HEADER = Path(__file__).resolve().parents[2] / "testroms" / "pages" / "mdfourier_script.h"

PROFILE_NAME = "PGM (IGS PGM) ICS2115"
SYNC_NAME = "ICS"


def build_profile() -> str:
    blocks = sig.build_blocks()
    # MonoBalanceBlock: a cumulative element index that lands inside the tone
    # block, used by MDFourier for L/R balance reference.
    balance = 40
    lines = [
        f"MDFourierAudioBlockFile 2.3",
        PROFILE_NAME,
        "[VideoModes] 1",
        f"{SYNC_NAME} {sig.FRAME_MS:.5f} {int(sig.SAMPLES_PER_FRAME)} "
        f"{sig.SYNC_FREQ} {sig.SYNC_PULSE_FRAMES} {sig.SYNC_PULSE_COUNT}",
        "CLK n",
        f"[MonoBalanceBlock] {balance}",
        f"[ToneLines] {len(blocks)}",
    ]
    lines.extend(b.profile_line() for b in blocks)
    return "\n".join(lines) + "\n"


def build_c_header() -> str:
    script = sig.build_script()
    packed = sig.pack_script(script)
    vt = sig.voice_template()
    rows = []
    for i in range(0, len(packed), 12):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in packed[i:i + 12]))
    body = "\n".join(rows)
    return f"""/* Auto-generated by util/mdfourier/make_profile.py --c-header — do not edit.
 * Packed MDFourier sequencer script + voice template for the standalone page.
 * Source of truth: util/mdfourier/signal.py */
#ifndef MDFOURIER_SCRIPT_H
#define MDFOURIER_SCRIPT_H

#define MDF_SCRIPT_COUNT   {len(script)}
#define MDF_TIMER_SCALE0   0x{sig.TIMER_SCALE0:02x}
#define MDF_TIMER_PRESET0  0x{sig.TIMER_PRESET0:02x}

#define MDF_LOOP_START     0x{sig.LOOP_START:05x}UL
#define MDF_LOOP_END       0x{sig.LOOP_END:05x}UL
#define MDF_OSC_CONF       0x{vt['osc_conf']:02x}
#define MDF_OSC_SADDR      0x{vt['osc_saddr']:02x}
#define MDF_PAN_CENTER     0x{vt['pan']:02x}

/* {len(packed)} bytes = {len(script)} x 8 (fc_hi fc_lo pan osc_conf action reserved ticks_hi ticks_lo) */
static const unsigned char mdf_script_data[{len(packed)}] = {{
{body}
}};

#endif /* MDFOURIER_SCRIPT_H */
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_MFN, help="output .mfn path")
    ap.add_argument("--c-header", nargs="?", const=DEFAULT_HEADER, type=Path,
                    help="also write the C script header for the standalone page")
    ap.add_argument("--print", action="store_true", help="print the profile to stdout")
    ap.add_argument("--short", action="store_true", help="small signal for fast sim smoke tests")
    args = ap.parse_args()

    sig.configure(short=args.short)
    profile = build_profile()
    args.out.write_text(profile)
    print(f"wrote {args.out} ({len(profile)} bytes)")
    if args.print:
        print(profile)

    if args.c_header is not None:
        header = build_c_header()
        args.c_header.write_text(header)
        print(f"wrote {args.c_header} ({len(header)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
