#!/usr/bin/env python3
"""Play the MDFourier signal on a target (sim or hardware) and capture a WAV.

The signal is generated by the Z80 timer-IRQ sequencer (driven over the
TestROM debug-link path), so the capture is sample-locked: a sim capture and a
hardware capture of the same signal line up sample-for-sample and differ only
by ICS2115 audio fidelity.

Examples:
    # fast simulator smoke test
    python3 util/mdfourier/run.py --target sim --short --out /tmp/mdf_sim.wav

    # full hardware capture
    python3 util/mdfourier/run.py --target hw --out /tmp/mdf_hw.wav
"""

from __future__ import annotations

import argparse
import struct
import sys
import wave
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from util.ics2115_remote import ICS2115Remote, Voice
from util.mdfourier import mdf_signal as sig


def _clamp16(v: int) -> int:
    if v > 32767:
        return 32767
    if v < -32768:
        return -32768
    return int(v)


def write_wav(path: Path, samples, rate: int) -> None:
    with wave.open(str(path), "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(rate)
        buf = bytearray()
        for l, r in samples:
            buf += struct.pack("<hh", _clamp16(l), _clamp16(r))
        w.writeframes(buf)


def resample(samples, src_rate: int, dst_rate: int):
    import math

    import numpy as np
    from scipy.signal import resample_poly

    g = math.gcd(src_rate, dst_rate)
    up, down = dst_rate // g, src_rate // g
    arr = np.asarray(samples, dtype=np.float64)
    out = resample_poly(arr, up, down, axis=0)
    out = np.clip(np.round(out), -32768, 32767).astype(np.int64)
    return [(int(l), int(r)) for l, r in out]


def make_voice() -> Voice:
    vt = sig.voice_template()
    v = Voice(
        osc_conf=vt["osc_conf"],
        osc_fc=vt["osc_fc"],
        vol_acc=vt["vol_acc"],
        vol_start=vt["vol_start"],
        vol_end=vt["vol_end"],
        vol_incr=vt["vol_incr"],
        vol_ctrl=vt["vol_ctrl"],
        pan=vt["pan"],
        osc_ctl=vt["osc_ctl"],
        vmode=vt["vmode"],
        osc_saddr=vt["osc_saddr"],
    )
    v.set_start_wave_addr(vt["start_wave"])
    v.set_end_wave_addr(vt["end_wave"])
    v.set_acc_wave_addr(vt["acc_wave"])
    return v


def open_target(args) -> ICS2115Remote:
    if args.target == "sim":
        remote = ICS2115Remote.open_sim(
            game=args.game, mra=args.mra, transport="debug_link",
            cwd=args.sim_cwd, executable=args.sim_exe,
            read_timeout_cycles=20_000_000, timeout_cycles_per_byte=20_000_000,
        )
        # Let the 68k boot into the ics_remote page and finish z80_ics_init so
        # the debug-link comms block is published before the first command.
        remote.picorom.sim.call("sim.run_frames", {"count": args.prime_frames})
        return remote
    # Hardware: always open with reset low, then reload firmware externally if
    # the board was physically reset (see project notes).
    return ICS2115Remote.open(args.hw_target, reset="low")


def capture(remote: ICS2115Remote, target: str, n_samples: int):
    import math

    audio = remote.open_audio()
    # Arm the sequence, then capture.  On sim no cycles run until we capture, so
    # the capture starts exactly at the sequence start.
    remote.mdf_load(sig.pack_script(sig.build_script()))
    remote.mdf_start(len(sig.build_script()), sig.TIMER_SCALE0, sig.TIMER_PRESET0)
    if target == "sim":
        return remote.capture_audio_frames(n_samples, timeout=None)
    # Hardware streams in real time; capture in blocks (the extractor's reliable
    # path — arm_frames is rejected by the firmware).  Grab extra blocks so the
    # end sync survives the small start offset, then trim.
    seconds = n_samples / sig.SAMPLE_RATE
    nblocks = math.ceil((n_samples + 0.5 * sig.SAMPLE_RATE) / 128)
    out: list = []
    for block in audio.capture_blocks(nblocks, timeout=seconds * 3 + 10):
        out.extend(block.samples)
    # Keep the extra tail (do not trim to n_samples): the hardware sequence is
    # already running when audio arms, so the capture starts a few ms late and
    # the comparison shifts by that lag — the tail must survive the shift.
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--target", choices=["sim", "hw"], required=True)
    ap.add_argument("--out", type=Path, required=True, help="output WAV path")
    ap.add_argument("--short", action="store_true", help="small signal for fast sim runs")
    ap.add_argument("--resample", type=int, default=0,
                    help="resample to this rate (default: native ~33075 Hz)")
    ap.add_argument("--margin", type=float, default=0.25,
                    help="extra seconds of capture after the signal")
    ap.add_argument("--game", default="pgm_test")
    ap.add_argument("--mra", default=None)
    ap.add_argument("--sim-cwd", default="sim")
    ap.add_argument("--sim-exe", default="./sim")
    ap.add_argument("--hw-target", default="pgm")
    ap.add_argument("--prime-frames", type=int, default=200,
                    help="sim: frames to run so the page boots before commands")
    args = ap.parse_args()

    sig.configure(short=args.short)
    script = sig.build_script()
    n_signal = sig.total_samples()
    n_capture = n_signal + int(args.margin * sig.SAMPLE_RATE)

    print(f"target={args.target} entries={len(script)} signal={n_signal} samples "
          f"({n_signal / sig.SAMPLE_RATE:.2f}s) capture={n_capture}")

    remote = open_target(args)
    try:
        # The ics_remote page already runs z80_ics_init at boot, so just confirm
        # the link (a full CMD_INIT would re-run init and overrun read timeouts).
        info = remote.ping()
        print(f"driver_magic=0x{info.driver_magic:04x}")
        # The Z80 sequencer ping-pongs voices 0 and 1, so both need the shared
        # voice template (loop region + full volume, stopped) before the start.
        remote.write_voice(0, make_voice())
        remote.write_voice(1, make_voice())
        samples = capture(remote, args.target, n_capture)
    finally:
        remote.close()

    print(f"captured {len(samples)} samples")
    rate = sig.SAMPLE_RATE_INT
    if args.resample and args.resample != rate:
        print(f"resampling {rate} -> {args.resample} Hz")
        samples = resample(samples, rate, args.resample)
        rate = args.resample

    write_wav(args.out, samples, rate)
    print(f"wrote {args.out} ({len(samples)} frames @ {rate} Hz)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
